name: Go CI/CD Pipeline

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  lint-test-build:
    name: Lint, Security, Test, and Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install linters
        run: |
          go install github.com/go-critic/go-critic/cmd/gocritic@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run Makefile commands
        run: make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
